Algoritmo "semnome"
// Disciplina   : [LPOO)
// Professor   : Aldo Henrique 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2019
Var
i:inteiro
num, den, soma: real


Inicio
soma <- 0
num <- -1

para i de 1 ate 50 faca
den <- i
soma <- soma + (num+2)/den
fimpara

escreval ("Soma= ", soma)


Fimalgoritmo